# Generated by Django 3.0.2 on 2020-02-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submitsys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='point_value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
