# Generated by Django 3.0.2 on 2020-02-25 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submitsys', '0002_submission_assignment'),
        ('submitsys', '0002_assignment_point_value'),
    ]

    operations = [
    ]
