# Generated by Django 3.0.2 on 2020-02-26 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submitsys', '0003_merge_20200224_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='CMSC 201', max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='submission',
            name='assignment',
        ),
        migrations.AddField(
            model_name='assignment',
            name='course_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='submitsys.Course'),
            preserve_default=False,
        ),
    ]
