# Generated by Django 3.0.2 on 2020-03-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submitsys', '0004_auto_20200226_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='student_num',
        ),
    ]
