# Generated by Django 3.0.2 on 2020-03-25 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submitsys', '0005_auto_20200303_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blank', models.BooleanField(default=True)),
                ('assignment_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submitsys.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='RubricSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='General', max_length=1000)),
                ('rubric_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submitsys.Rubric')),
            ],
        ),
        migrations.CreateModel(
            name='RubricItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=1000)),
                ('possible_points', models.IntegerField()),
                ('is_optional', models.BooleanField()),
                ('section_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submitsys.RubricSection')),
            ],
        ),
    ]
