# Generated by Django 3.0.2 on 2020-04-08 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submitsys', '0006_rubric_rubricitem_rubricsection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='student',
            new_name='student_fk',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='file_name',
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=15)),
                ('file_contents', models.TextField()),
                ('submission_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submitsys.Submission')),
            ],
        ),
    ]
