# Generated by Django 3.0.2 on 2020-04-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submitsys', '0011_auto_20200415_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_fname',
            field=models.TextField(default='NULL'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_lname',
            field=models.TextField(default='NULL'),
        ),
    ]
