# Generated by Django 3.0.2 on 2020-04-22 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submitsys', '0013_assignment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 15, 59, 31, 123404)),
        ),
    ]
